#!/bin/bash
read -p "Enter 3 numbers: " num1 num2 num3
 if [[ num1 -gt num2 && num1 -gt num3 ]]; then
	echo "Number $a is greatest"
elif [[ num2 -gt num1 && num2 -gt num3 ]]; then
	echo "Number $num2 is greatest"
else
	echo "Number $num3 is greatest"
fi

