#!/bin/bash
read -p "Enter 3 numbers: " a b c
 if [[ a -gt b && a -gt c ]]; then
	echo "Number $a is greatest"
elif [[ b -gt a && b -gt c ]]; then
	echo "Number $b is greatest"
else
	echo "Number $c is greatest"
fi

